title: >
  Programming Language Foundations in Agda

# the author field should not be used in the template
author: Wen Kokke

# to include a new contributor, add:
# name, email, (github_username or twitter_username)
contributors:
  - name: Wen Kokke
    email: wen.kokke@ed.ac.uk
    github_username:  wenkokke
    twitter_username: wenkokke
  - name: Philip Wadler
    email: wadler@inf.ed.ac.uk
    github_username:  wadler
    twitter_username: philipwadler

description: > 
  Programming Language Foundations in Agda

# include disqus to allow comments e.d.
disqus:
  shortname: wenkokke

baseurl: ""
url: "https://plfa.ed.inf.ac.uk"
plugins:
  - jekyll-feed
markdown: kramdown
theme: minima
exclude:
  - "hs/"
  - "src/"
  - "extra/"
  - "vendor/"
  - "Notes.md"
  - "*.lagda"
  - "Gemfile"
  - "Gemfile.lock"
